apiVersion: v2
description: Airflow is a platform to programmatically author, schedule and monitor workflows
name: airflow
type: application
version: 0.1.0
appVersion: 1.10.10
icon: https://airflow.apache.org/_images/pin_large.png
home: https://airflow.apache.org/
sources:
  - https://airflow.apache.org/
keywords:
  - airflow
  - workflow
  - dag
dependencies:
  - name: postgresql
    version: 8.6.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: redis
    version: 10.5.7
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
