apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: password
            - name: PGADMIN_LISTEN_PORT
              value: "80"
          ports:
            - containerPort: 80
          # volumeMounts:
          #   - name: pgadmin
          #     mountPath: /var/lib/pgadmin
      # volumes:
      #   - name: pgadmin
      #     persistentVolumeClaim:
      #       claimName: pgadmin-pvc
