kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin-pvc
  labels:
    app: pgadmin
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pgadmin-pv
  # storageClassName: microk8s-hostpath
  volumeMode: Filesystem
